// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ArtistId } from './Artist';
import type { TagId } from './Tag';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.artist_tag */
export type ArtistTagId = number & { __brand: 'ArtistTagId' };

/** Represents the table public.artist_tag */
export default interface ArtistTagTable {
  id: ColumnType<ArtistTagId, ArtistTagId | undefined, ArtistTagId>;

  artist: ColumnType<ArtistId, ArtistId, ArtistId>;

  tag: ColumnType<TagId, TagId, TagId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type ArtistTag = Selectable<ArtistTagTable>;

export type NewArtistTag = Insertable<ArtistTagTable>;

export type ArtistTagUpdate = Updateable<ArtistTagTable>;
