// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ArtistId } from './Artist';
import type { UserId } from './User';
import type { default as ValidationStatus } from './ValidationStatus';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.artist_validation */
export type ArtistValidationId = number & { __brand: 'ArtistValidationId' };

/** Represents the table public.artist_validation */
export default interface ArtistValidationTable {
  id: ColumnType<ArtistValidationId, ArtistValidationId | undefined, ArtistValidationId>;

  artist: ColumnType<ArtistId, ArtistId, ArtistId>;

  admin: ColumnType<UserId, UserId, UserId>;

  status: ColumnType<ValidationStatus, ValidationStatus | undefined, ValidationStatus>;

  comments: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<string, string | undefined, string>;

  updated_at: ColumnType<string, string | undefined, string>;
}

export type ArtistValidation = Selectable<ArtistValidationTable>;

export type NewArtistValidation = Insertable<ArtistValidationTable>;

export type ArtistValidationUpdate = Updateable<ArtistValidationTable>;
