// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ArtistId } from './Artist';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.artist_event */
export type ArtistEventId = number & { __brand: 'ArtistEventId' };

/** Represents the table public.artist_event */
export default interface ArtistEventTable {
  id: ColumnType<ArtistEventId, ArtistEventId | undefined, ArtistEventId>;

  artist: ColumnType<ArtistId, ArtistId, ArtistId>;

  title: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  starts_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  ends_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  location: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type ArtistEvent = Selectable<ArtistEventTable>;

export type NewArtistEvent = Insertable<ArtistEventTable>;

export type ArtistEventUpdate = Updateable<ArtistEventTable>;
