// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ArtistId } from './Artist';
import type { CategoryId } from './Category';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.artist_category */
export type ArtistCategoryId = number & { __brand: 'ArtistCategoryId' };

/** Represents the table public.artist_category */
export default interface ArtistCategoryTable {
  id: ColumnType<ArtistCategoryId, ArtistCategoryId | undefined, ArtistCategoryId>;

  artist: ColumnType<ArtistId, ArtistId, ArtistId>;

  category: ColumnType<CategoryId, CategoryId, CategoryId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type ArtistCategory = Selectable<ArtistCategoryTable>;

export type NewArtistCategory = Insertable<ArtistCategoryTable>;

export type ArtistCategoryUpdate = Updateable<ArtistCategoryTable>;
