// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.artist */
export type ArtistId = number & { __brand: 'ArtistId' };

/** Represents the table public.artist */
export default interface ArtistTable {
  id: ColumnType<ArtistId, ArtistId | undefined, ArtistId>;

  name: ColumnType<string, string, string>;

  bio: ColumnType<string | null, string | null, string | null>;

  created_by: ColumnType<UserId, UserId, UserId>;

  created_at: ColumnType<string, string | undefined, string>;

  updated_at: ColumnType<string, string | undefined, string>;
}

export type Artist = Selectable<ArtistTable>;

export type NewArtist = Insertable<ArtistTable>;

export type ArtistUpdate = Updateable<ArtistTable>;
