// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.category */
export type CategoryId = number & { __brand: 'CategoryId' };

/** Represents the table public.category */
export default interface CategoryTable {
  id: ColumnType<CategoryId, CategoryId | undefined, CategoryId>;

  name: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Category = Selectable<CategoryTable>;

export type NewCategory = Insertable<CategoryTable>;

export type CategoryUpdate = Updateable<CategoryTable>;
