// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DropdownCategoryId } from './DropdownCategory';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.dropdown_option */
export type DropdownOptionId = number & { __brand: 'DropdownOptionId' };

/** Represents the table public.dropdown_option */
export default interface DropdownOptionTable {
  id: ColumnType<DropdownOptionId, DropdownOptionId | undefined, DropdownOptionId>;

  category: ColumnType<DropdownCategoryId, DropdownCategoryId, DropdownCategoryId>;

  value: ColumnType<string, string, string>;

  label: ColumnType<string, string, string>;

  active: ColumnType<boolean, boolean | undefined, boolean>;

  index: ColumnType<number, number, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type DropdownOption = Selectable<DropdownOptionTable>;

export type NewDropdownOption = Insertable<DropdownOptionTable>;

export type DropdownOptionUpdate = Updateable<DropdownOptionTable>;
