// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ArtistId } from './Artist';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.gallery_image */
export type GalleryImageId = number & { __brand: 'GalleryImageId' };

/** Represents the table public.gallery_image */
export default interface GalleryImageTable {
  id: ColumnType<GalleryImageId, GalleryImageId | undefined, GalleryImageId>;

  artist: ColumnType<ArtistId, ArtistId, ArtistId>;

  path: ColumnType<string, string, string>;

  caption: ColumnType<string | null, string | null, string | null>;

  file_type: ColumnType<string, string, string>;

  alt_text: ColumnType<string | null, string | null, string | null>;

  index: ColumnType<number, number, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type GalleryImage = Selectable<GalleryImageTable>;

export type NewGalleryImage = Insertable<GalleryImageTable>;

export type GalleryImageUpdate = Updateable<GalleryImageTable>;
