// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as KyselyMigrationTable } from './KyselyMigration';
import type { default as KyselyMigrationLockTable } from './KyselyMigrationLock';
import type { default as UserTable } from './User';
import type { default as ArtistTable } from './Artist';
import type { default as UserFavoriteTable } from './UserFavorite';
import type { default as ArtistLinkTable } from './ArtistLink';
import type { default as ArtistEventTable } from './ArtistEvent';
import type { default as GalleryImageTable } from './GalleryImage';
import type { default as CategoryTable } from './Category';
import type { default as ArtistTagTable } from './ArtistTag';
import type { default as ArtistValidationTable } from './ArtistValidation';

export default interface PublicSchema {
  kysely_migration: KyselyMigrationTable;

  kysely_migration_lock: KyselyMigrationLockTable;

  user: UserTable;

  artist: ArtistTable;

  user_favorite: UserFavoriteTable;

  artist_link: ArtistLinkTable;

  artist_event: ArtistEventTable;

  gallery_image: GalleryImageTable;

  category: CategoryTable;

  artist_tag: ArtistTagTable;

  artist_validation: ArtistValidationTable;
}
