// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as ArtistTable } from './Artist';
import type { default as UserTable } from './User';

export default interface PublicSchema {
  artist: ArtistTable;

  user: UserTable;
}
