// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ArtistId } from './Artist';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user_favorite */
export type UserFavoriteId = number & { __brand: 'UserFavoriteId' };

/** Represents the table public.user_favorite */
export default interface UserFavoriteTable {
  id: ColumnType<UserFavoriteId, UserFavoriteId | undefined, UserFavoriteId>;

  user: ColumnType<UserId, UserId, UserId>;

  artist: ColumnType<ArtistId, ArtistId, ArtistId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type UserFavorite = Selectable<UserFavoriteTable>;

export type NewUserFavorite = Insertable<UserFavoriteTable>;

export type UserFavoriteUpdate = Updateable<UserFavoriteTable>;
