// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.validation_status */
enum ValidationStatus {
  pending = 'pending',
  approved = 'approved',
  rejected = 'rejected',
};

export default ValidationStatus;
