// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as SchemaMigrationsTable } from './SchemaMigrations';
import type { default as SubscriptionTable } from './Subscription';
import type { default as MessagesTable } from './Messages';
import type { default as UserDefinedFilterTable } from './UserDefinedFilter';
import type { default as WalRlsTable } from './WalRls';
import type { default as WalColumnTable } from './WalColumn';

export default interface RealtimeSchema {
  schema_migrations: SchemaMigrationsTable;

  subscription: SubscriptionTable;

  messages: MessagesTable;

  user_defined_filter: UserDefinedFilterTable;

  wal_rls: WalRlsTable;

  wal_column: WalColumnTable;
}
